// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhJ0XXj1JtD_ONh9w8K6kvxiJqtgxfOyo',
    appId: '1:955313604600:web:7218a7014750070dab380d',
    messagingSenderId: '955313604600',
    projectId: 'event-discovery-a86e7',
    authDomain: 'event-discovery-a86e7.firebaseapp.com',
    storageBucket: 'event-discovery-a86e7.appspot.com',
    measurementId: 'G-Z1WQZTEM55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvuf6WKyX9qVagHMDb2NAgxACTnM2Dzc0',
    appId: '1:955313604600:android:23b826afea7a68bbab380d',
    messagingSenderId: '955313604600',
    projectId: 'event-discovery-a86e7',
    storageBucket: 'event-discovery-a86e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjjIcRDeLBDzWmTvCAvdVyiXqla_-k8FA',
    appId: '1:955313604600:ios:b264f2d0814ec78aab380d',
    messagingSenderId: '955313604600',
    projectId: 'event-discovery-a86e7',
    storageBucket: 'event-discovery-a86e7.appspot.com',
    iosBundleId: 'com.example.eventDiscovery',
  );
}
